name: Deploy

env:
  NODE_OPTIONS: '--max_old_space_size=6144'

on:
  push:
    branches:
      - release

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v1
        with:
          deps-server-version: beta
          skip-upload: false
          skip-deploy: true
          skip-release: true
          skip-readme: true
          bundle-command: pnpm bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_DEV }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_DEV }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
